apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers: 
      - name: playground-container
        image: peytma/devops_test_image:v1.0
        ports:
        - containerPort: 80
